import type { Metadata } from "next";
import { Lato } from 'next/font/google';
import { AppSidebar } from "@/components/app-sidebar";
import NextTopLoader from 'nextjs-toploader';
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import "@/app/globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import ThemeProvider from "@/components/ThemeToggle/theme-provider";



const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader showSpinner={false} />
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <Header />
              <main>
                {children}
              </main>
            </SidebarInset>
          </SidebarProvider>
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
